import type { Metadata } from "next";
import { LegalPage } from "../legal";

export const metadata: Metadata = { title: "Termos de Uso | Excel Avançado", description: "Condições de compra, acesso e utilização do treinamento Excel Avançado." };

const sections = [
  { title: "Aceitação", paragraphs: ["Ao acessar este site, realizar uma compra ou utilizar a área de membros, você concorda com estes Termos de Uso e com a Política de Privacidade. Se não concordar, não prossiga com a contratação."] },
  { title: "Sobre o treinamento", paragraphs: ["O Excel Avançado é um curso livre, online e de caráter educacional, composto por videoaulas e materiais complementares. O conteúdo abrange assuntos do básico ao avançado, como organização de dados, fórmulas, análises, gráficos, dashboards e introdução a automações.", "O certificado emitido comprova a conclusão do treinamento. Ele não equivale a diploma acadêmico, certificação profissional regulamentada ou reconhecimento pelo MEC."] },
  { title: "Compra e acesso", items: ["O acesso é enviado ao e-mail informado após a confirmação do pagamento.", "O comprador deve fornecer dados corretos e manter suas credenciais protegidas.", "O acesso é pessoal e não pode ser vendido, cedido ou compartilhado com terceiros.", "Problemas de acesso devem ser informados pelo canal de suporte da área de membros."] },
  { title: "Requisitos técnicos", paragraphs: ["Para acompanhar o curso, o aluno precisa de conexão com a internet e dispositivo compatível. A licença do Microsoft Excel, sistema operacional, equipamentos e serviços de internet não estão incluídos na compra."] },
  { title: "Materiais e bônus", paragraphs: ["Apostilas, arquivos práticos e planilhas bônus são destinados ao uso pessoal do comprador. O acervo de mais de 5 mil planilhas é um bônus de modelos variados, não uma coleção de 5 mil aulas ou exercícios vinculados individualmente ao treinamento.", "A organização, a apresentação e a disponibilidade de itens bônus podem ser ajustadas para melhorar a experiência, sem reduzir o conteúdo principal adquirido."] },
  { title: "Propriedade intelectual", paragraphs: ["A marca, os textos, as aulas, o design e os materiais disponibilizados são protegidos por direitos autorais e outras normas aplicáveis. É proibido copiar, gravar, revender, redistribuir, disponibilizar publicamente, remover identificações ou explorar comercialmente o conteúdo sem autorização escrita."] },
  { title: "Certificado", paragraphs: ["O certificado digital fica disponível após a conclusão do treinamento e o cumprimento do período de liberação informado na área de membros. O nome do certificado será baseado nos dados cadastrados pelo aluno."] },
  { title: "Suporte", paragraphs: ["O suporte disponível é destinado principalmente a questões de acesso e funcionamento da plataforma. Respostas pedagógicas individuais, consultoria, correção de projetos ou acompanhamento particular só estarão incluídos quando forem expressamente oferecidos na página de venda."] },
  { title: "Garantia e cancelamento", paragraphs: ["O comprador pode avaliar o treinamento por 7 dias contados da compra. Dentro desse prazo, o cancelamento deve ser solicitado pelos canais e condições apresentados no checkout, observadas as regras aplicáveis à contratação digital."] },
  { title: "Responsabilidades", paragraphs: ["O curso tem finalidade educacional e não garante emprego, promoção, renda, salário, resultado profissional específico ou domínio imediato do Excel. O progresso depende, entre outros fatores, da dedicação, prática, equipamento e contexto de cada aluno.", "Podemos realizar manutenções e ajustes técnicos. Interrupções temporárias serão tratadas em prazo razoável, sem gerar responsabilidade por fatores externos, como falhas de internet, serviços de terceiros ou equipamentos do usuário."] },
  { title: "Conduta e suspensão", paragraphs: ["O acesso poderá ser suspenso em caso de fraude, violação destes termos, compartilhamento de conta, tentativa de cópia indevida, ataque à plataforma ou uso que prejudique outros usuários. Antes de uma medida definitiva, o caso poderá ser analisado e o comprador contatado quando apropriado."] },
  { title: "Atualizações e legislação", paragraphs: ["Estes termos podem ser atualizados para refletir mudanças no produto, nas plataformas utilizadas ou na legislação. A versão vigente ficará disponível nesta página.", "Aplica-se a legislação brasileira. Questões decorrentes desta relação serão tratadas conforme as normas de proteção ao consumidor e demais leis aplicáveis."] },
];

export default function TermsPage() {
  return <LegalPage eyebrow="CONDIÇÕES DE ACESSO E UTILIZAÇÃO" title="Termos de Uso" intro="Aqui estão as regras para compra, acesso e uso responsável do treinamento e dos materiais do Excel Avançado." sections={sections} />;
}
